services:
  paneo:
    image: ghcr.io/codewec/paneo:dev
    container_name: paneo
    user: "${UID}:${GID}"
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ${PANEO_SOURCE_1}:/data/source-1
      - ${PANEO_SOURCE_2}:/data/source-2
      - ${PANEO_DATA_DIR}:/app/.paneo
